//@ sourceMappingURL=app.map
// Generated by CoffeeScript 1.6.1

/*
Module dependencies.
*/


(function() {
  var app, express, fs, http, https, path, routes;

  express = require("express");

  routes = require("./routes");

  http = require("http");

  path = require("path");

  https = require("https");

  fs = require("fs");

  /*
  opts = {
      key:    fs.readFileSync("ssl/funkmod.key"),
      cert:   fs.readFileSync("ssl/funkmod.crt"),
      ca:     fs.readFileSync("ssl/funkmod.crt"),
      requestCert:        true,
      rejectUnauthorized: true,
      passphrase: "password"
  }
  */


  app = express();

  app.configure(function() {
    app.set("port", process.env.PORT || 3001);
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](path.join(__dirname, "public")));
  });

  app.configure("development", function() {
    return app.use(express.errorHandler());
  });

  /*
  HTTPS Routing controls
  */


  app.get("/", function(req, res) {
    return res.redirect("/index.html");
  });

  app.get("/api/results", function(req, res) {});

  app.get("/api/upload", routes.upload);

  http.createServer(app).listen(app.get("port"), "0.0.0.0", function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

  /*
  HTTP Routing controls
  */


}).call(this);
