// Generated by CoffeeScript 1.3.3
(function() {
  var client, conString, pg;

  pg = require("pg");

  conString = "tcp://admin:password@localhost/forms";

  client = new pg.Client(conString);

  client.connect();

  exports.Reason = function(callback) {
    var cities, places, query, reasons;
    query = client.query('SELECT r.name, r.id FROM reasons as r');
    reasons = [];
    query.on("row", function(row) {
      return reasons.push(row);
    });
    query = client.query('SELECT p.name, p.city_id, p.id FROM places as p');
    places = [];
    query.on("row", function(row) {
      return places.push(row);
    });
    query = client.query('SELECT c.c_name, c.id FROM cities as c');
    cities = [];
    query.on("row", function(row) {
      return cities.push(row);
    });
    return query.on("end", function() {
      return callback(reasons, places, cities);
    });
  };

  exports.ViewForm = function(title, callback) {
    var form, query;
    form = [];
    query = client.query("SELECT r.name, p.name, c.c_name, f.title, f.filename, f.is_pediatric\nFROM\nreasons as r, places as p, forms as f, cities as c\nWHERE\nf.reason_id = r.id AND f.place_id = p.id AND p.city_id = c.id AND f.title = '" + title + "';");
    query.on("row", function(row) {
      return form.push;
    });
    console.log(title);
    return query.on("end", function() {
      return callback(form);
    });
  };

  exports.DelForm;

  exports.AddCity = function(new_city) {
    var query;
    return query = client.query("INSERT INTO cities (c_name) \nVALUES ('" + new_city + "');");
  };

  exports.AddReason = function(new_reason) {
    var query;
    return query = client.query("INSERT INTO reasons (name) \nVALUES ('" + new_reason + "');");
  };

  exports.AddInst = function(new_place) {
    var query;
    return query = client.query("INSERT INTO places (name, city_id) \nVALUES ('" + new_place.name + "', " + new_place.city_id + ");");
  };

  exports.Upload = function(new_form) {
    var query;
    return query = client.query("INSERT INTO forms (title, is_pediatric, place_id, reason_id) \nVALUES ('" + new_form.title + "', '" + new_form.rid + "', " + new_form.pid + ", " + new_form.rid + ");");
  };

  exports.Search = function(callback) {
    var query, results;
    query = client.query('SELECT r.name, p.name, c.c_name, f.title, f.filename, f.is_pediatric\nFROM\nreasons as r, places as p, forms as f, cities as c\nWHERE\nf.reason_id = r.id AND f.place_id = p.id AND p.city_id = c.id;');
    results = [];
    query.on("row", function(row) {
      return results.push(row);
    });
    return query.on("end", function() {
      return callback(results);
    });
  };

}).call(this);
