//@ sourceMappingURL=models.map
// Generated by CoffeeScript 1.6.1
(function() {
  var client, conString, pg;

  pg = require("pg");

  conString = "tcp://admin:halflife2@localhost/forms";

  client = new pg.Client(conString);

  client.connect();

  exports.Search = function(term, callback) {
    var query, results;
    query = client.query("SELECT r.name, s.name, p.name, p.city, f.title FROM reasons as r, services as s, places as p, forms as f");
    /*  
    r.name, s.name, p.name, p.city, f.title
    FROM
    reasons as r, services as s, places as p, forms as f
    WHERE
    f.reason_id = r.id AND f.place_id = p.id AND f.service_id = s.id
    AND (
      r.name ILIKE '%#{term}%'
      OR s.name ILIKE '%#{term}%'
      OR p.name ILIKE '%#{term}%'
      OR p.city ILIKE '%#{term}%'
      OR f.title ILIKE '%#{term}%'
    )
    """
    */

    results = [];
    query.on("row", function(row) {
      results.push(row);
      return console.log(results);
    });
    return query.on("end", function() {
      return callback(results);
    });
  };

}).call(this);
