// Generated by CoffeeScript 1.5.0
(function() {
  var client, conString, pg, query;

  pg = require("pg");

  conString = "tcp://postgres:1234@localhost/postgres";

  client = new pg.Client(conString);

  client.connect();

  client.query("CREATE TEMP TABLE beatles(name varchar(10), height integer, birthday timestamptz)");

  client.query("INSERT INTO beatles(name, height, birthday) values($1, $2, $3)", ["John", 68, new Date(1944, 10, 13)]);

  query = client.query("SELECT * FROM beatles WHERE name = $1", ["John"]);

  query.on("row", function(row) {
    console.log(row);
    console.log("Beatle name: %s", row.name);
    console.log("Beatle birth year: %d", row.birthday.getYear());
    return console.log("Beatle height: %d' %d\"", Math.floor(row.height / 12), row.height % 12);
  });

  query.on("end", function() {
    return client.end();
  });

}).call(this);
