// Generated by CoffeeScript 1.6.3
(function() {
  String.prototype.hashCode = function() {
    var char, hash, i, l;
    hash = 0;
    i = void 0;
    char = void 0;
    if (this.length === 0) {
      return hash;
    }
    i = 0;
    l = this.length;
    while (i < l) {
      char = this.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash |= 0;
      i++;
    }
    return Math.abs(hash);
  };

}).call(this);
